SELECT TOP (1000) [id]
      ,[labourOwnership]
      ,[uploadAadhaarFront]
      ,[uploadAadhaarBack]
      ,[name]
      ,[aadhaarNumber]
      ,[dateOfBirth]
      ,[contactNumber]
      ,[gender]
      ,[dateOfJoining]
      ,[address]
      ,[pincode]
      ,[taluka]
      ,[district]
      ,[village]
      ,[state]
      ,[emergencyContact]
      ,[photoSrc]
      ,[bankName]
      ,[branch]
      ,[accountNumber]
      ,[ifscCode]
      ,[projectName]
      ,[labourCategory]
      ,[department]
      ,[workingHours]
      ,[contractorName]
      ,[contractorNumber]
      ,[status]
      ,[IsApproved]
      ,[LabourID]
      ,[designation]
      ,[title]
      ,[Nationality]
      ,[Marital_Status]
      ,[Payment_Mode]
      ,[companyName]
      ,[Employee_Type]
      ,[Current_Status]
      ,[Seating_Office]
      ,[Period]
      ,[From_Date]
      ,[Group_Join_Date]
      ,[uploadIdProof]
      ,[Reject_Reason]
      ,[Inducted_By]
      ,[Induction_Date]
      ,[ValidTill]
      ,[location]
      ,[OnboardName]
      ,[uploadInductionDoc]
      ,[expiryDate]
      ,[CalenderType]
      ,[ConfirmDate]
      ,[retirementDate]
      ,[SalaryBu]
      ,[WorkingBu]
      ,[CreationDate]
      ,[businessUnit]
      ,[departmentId]
      ,[designationId]
      ,[LedgerId]
      ,[GradeId]
      ,[labourCategoryId]
      ,[empId]
      ,[departmentName]
      ,[ApproveLabourDate]
      ,[RejectLabourDate]
      ,[EditLabourDate]
      ,[ResubmitLabourDate]
      ,[hideResubmit]
      ,[isResubmit]
      ,[OnboardingProjectName]
      ,[OnboardingBusinessUnit]
      ,[isSiteTransfer]
      ,[isCompanyTransfer]
  FROM [LabourOnboardingForm_TEST].[dbo].[labourOnboarding]


   SELECT 
        status, 
        COUNT(*) AS count 
      FROM labourOnboarding 
      WHERE status IN ('Approved', 'Desable', 'Pending', 'Rejected', 'Resubmitted')
      GROUP BY status

       SELECT 
        status, 
        COUNT(*) AS count 
      FROM labourOnboarding 
      WHERE status IN ('Approved', 'Disable', 'Pending', 'Rejected', 'Resubmitted')
      GROUP BY status