SELECT TOP (1000) [AttendanceId]
      ,[LabourId]
      ,[Date]
      ,[FirstPunch]
      ,[LastPunch]
      ,[TotalHours]
      ,[Overtime]
      ,[Status]
      ,[CreationDate]
      ,[FirstPunchManually]
      ,[LastPunchManually]
      ,[OvertimeManually]
      ,[RemarkManually]
      ,[FirstPunchAttendanceId]
      ,[FirstPunchDeviceId]
      ,[LastPunchAttendanceId]
      ,[LastPunchDeviceId]
      ,[TimesUpdate]
      ,[EditUserName]
      ,[LastUpdatedDate]
      ,[WorkingHours]
      ,[OnboardName]
      ,[projectName]
      ,[ApprovalStatus]
      ,[ApprovalDate]
      ,[ApprovalRemark]
      ,[SentForApproval]
      ,[RejectAttendanceReason]
      ,[RejectedDate]
      ,[isRejectedAttendance]
      ,[isApprovedAttendance]
      ,[PayrollCalRoundOffOvertime]
      ,[projectIdFromDevicefirstPunch]
      ,[projectIdFromDeviceLastPunch]
  FROM [LabourOnboardingForm_TEST].[dbo].[LabourAttendanceDetails]


  