SELECT TOP (1000) [ApprovalID]
      ,[WageID]
      ,[AdminID]
      ,[ApprovalStatus]
      ,[WagesEditedBy]
      ,[ApprovalDate]
      ,[RejectionDate]
      ,[EditDate]
      ,[Remarks]
      ,[LabourID]
      ,[DailyWages]
      ,[MonthlyWages]
      ,[FixedMonthlyWages]
      ,[WeeklyOff]
      ,[PayStructure]
      ,[OnboardName]
      ,[ApprovalStatusWages]
      ,[CreatedAt]
      ,[PerHourWages]
      ,[EffectiveDate]
      ,[YearlyWages]
      ,[name]
  FROM [LabourOnboardingForm_TEST].[dbo].[WagesAdminApprovals]



   select LabourID, WagesEditedBy, ProjectName, ApprovalStatusWages from [LabourMonthlyWages];
   select LabourID, currentSite, adminStatus, createdAt, siteTransferBy from [dbo].[AdminSiteTransferApproval]